# This workflow is to list using eslint and prettier
# The following plugins are configured for each
# eslint: typescript/recommended, next/recommended
# prettier: tailwindcss/plugin

name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]
  schedule:
    - cron: "36 2 * * 2"

jobs:
  eslint:
    name: Run lint and format scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # add result for the eslint to the sarif files
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@9.29.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          npm install @types/eslint__js@8.42.3
          npm install typescript-eslint@8.34.1
          npm install @typescript-eslint/eslint-plugin@latest
          npm install @next/eslint-plugin-next@15.3.3
          npm install eslint-config-next@15.3.3
          npm install prettier
          npm install prettier-plugin-tailwindcss
        working-directory: "./webapp"

      - name: Run ESLint
        run: npm run lint:ci
        continue-on-error: false
        working-directory: "./webapp"

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
          
      - name: Run Prettier check
        run: npm run format:ci
        continue-on-error: false
        working-directory: "./webapp"
